stages:
  - test
  - build

variables:
  SIGNING_KEY: b229658610a28f3fb4a6e274c17a261913900036e36c3addf0720824c576c6e3f66b2ef0538d98856278c1374a5a055df262a8b6697ad3c9190bf1c3d403bcab

fast-api-unit-test-job:
  image: python:3.10-bullseye
  stage: test
  script:
    - cd api
    - pip install -r requirements.txt
    - python -m pytest

lint-python-project-job:
  image: python:3.10-bullseye
  stage: test
  script:
    - pip install flake8
    - flake8 api
