volumes:
  plunge-data:
    external: true
  pg-admin:
    external: true
  jwtdown-db-data:
    external: true
services:
  fastapi:
    environment:
      CORS_HOST: ${FAST_API_CORS_HOST}
      DATABASE_URL: postgresql://plunge:plunge@postgres/plunge_db
      SIGNING_KEY: ${FAST_API_SIGNING_KEY}
      WAIT_HOSTS: postgres:5432
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
      OPEN_WEATHER_API_KEY: ${FAST_API_OPEN_WEATHER_API_KEY}
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
  postgres:
    build:
      context: data
      dockerfile: Dockerfile.dev
    image: postgres:14.5-bullseye
    volumes:
      - plunge-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: plunge
      POSTGRES_USER: plunge
      POSTGRES_DB: plunge_db
    ports:
      - 15432:5432
  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: plunge@plunge.com
      PGADMIN_DEFAULT_PASSWORD: plunge
      PGADMIN_DISABLE_POSTFIX: 1

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - '3000:3000'
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: '0.0.0.0'
      PUBLIC_URL: ${PUBLIC_URL}
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}
      REACT_APP_GOOGLE_MAPS_API_KEY: ${REACT_APP_GOOGLE_MAPS_API_KEY}
