volumes:
  plunge-data:
    external: true
  pg-admin:
    external: true
  jwtdown-db-data:
    external: true
services:
  fastapi:
    environment:
      CORS_HOST: http://localhost:3000
      DATABASE_URL: postgresql://plunge:plunge@postgres/plunge_db
      SIGNING_KEY: b229658610a28f3fb4a6e274c17a261913900036e36c3addf0720824c576c6e3f66b2ef0538d98856278c1374a5a055df262a8b6697ad3c9190bf1c3d403bcab
      WAIT_HOSTS: postgres:5432
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
  postgres:
    build:
      context: data
      dockerfile: Dockerfile.dev
    image: postgres:14.5-bullseye
    volumes:
      - plunge-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: plunge
      POSTGRES_USER: plunge
      POSTGRES_DB: plunge_db
    ports:
      - 15432:5432
  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: plunge@plunge.com
      PGADMIN_DEFAULT_PASSWORD: plunge
      PGADMIN_DISABLE_POSTFIX: 1

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}
